# driver class
database.driver=com.mysql.cj.jdbc.Driver
# url
database.url=jdbc:mysql://127.0.0.1:3307/v111_migration_test?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
# userName
database.user=root
# password
database.password=97mEl1PHFfJGyR2Tu0WVUaiO
